theme: minimal-mistakes-jekyll

locale: en-GB
title: Custom GPTs by dev.joynt.co.uk
subtitle: GPTs created by joynt.co.uk
description: >
  A collection of GPTs made for use in ChatGPT Plus, providing customized
  ChatGPT system instructions, use of bespoke Knowledge Documents and access to
  remote API endpoints.
url: https://gpt.joynt.co.uk
baseurl: /
show_downloads: false

author:
  name: Charles Joynt
  url: https://dev.joynt.co.uk

repository: cjj1977/gpt-docs