plugins:
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes@4.24.0

locale: en-GB
title: gpt.joynt.co.uk
subtitle: Chat with my GPTs
description: >
  A collection of GPTs made for use in ChatGPT Plus, providing customized
  ChatGPT system instructions, use of bespoke Knowledge Documents and access to
  remote API endpoints via GPT Actions.
url: https://gpt.joynt.co.uk
baseurl: /
show_downloads: false
include: ["_pages"]

author:
  name: Charles Joynt
  url: https://dev.joynt.co.uk

defaults:
  # pages
  - scope:
      path: ""
    values:
      sidebar:
        nav: "docs"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
    
repository: cjj1977/gpt-docs